<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Swift3.0语法速查手册 - 错误处理</title>
    <link rel="stylesheet" href="../source/site.css">
    <link rel="stylesheet" href="../source/prism.css">
    <link rel="shortcut icon" href="../source/favicon.ico">
</head>
<body>
<div id="container">
    <h1>
        <a href='#'>Swift3.0语法速查手册</a>
        <span class="topic">错误处理</span>
    </h1>

    <main>
        <table>
            <tbody>
            <tr>
                <td class='docs'></td>
                <td class='code'>
                    <pre><code class='language-swift'> </code></pre>
                </td>
            </tr>

            <tr>
                <td class='docs'> 1. 错误处理: swift在运行时能够对错误进行处理并给出相应的操作 </td>
                <td class='code'>
                    <pre><code class='language-swift'>// 处理错误的几种方式:  1. 把错误传递给调用函数,然后使用do-catch语句处理错误
//                   2. 将错误作为可选类型处理
//                   3. 使用断言处理

// 定义错误类型
enum CustomErrorType: Error {           // 通过枚举构建一组相关的错误状态
    case errorReason1
    case errorReason2
    case errorReason3
}
                    </code></pre>
                </td>
            </tr>

            <tr>
                <td class='docs'> 2. 通过throwing函数传递错误 </td>
                <td class='code'>
                    <pre><code class='language-swift'>// throwing函数: 在参数列表后面加throws,表示可以抛出错误
class ThrowClass {
    var num: Int?                      // 根据num值抛出异常
    func throwFunc() throws {          // 如果有返回类型,throws需要写在(->)前面
        guard num == 1 else {          // 当num != 1 执行throw抛出异常
            throw CustomErrorType.errorReason1   // 异常会传递到函数被调用的作用域
        }                              // throw语句会立刻退出当前方法,相当于return
        guard num == 2 else {
            throw CustomErrorType.errorReason2
        }
        guard num == 3 else {
            throw CustomErrorType.errorReason3
        }
    }
}</code></pre>
                </td>
            </tr>


            <tr>
                <td class='docs'> 3. 通过Do-Catch处理throwing函数传递的错误 </td>
                <td class='code'>
                    <pre><code class='language-swift'>let throwClass = ThrowClass()
throwClass.num = 4

do {
    try throwClass.throwFunc()
}catch CustomErrorType.errorReason1 {   // 根据返回错误类型,执行这个{}
    print("errorReason1")               // errorReason1
}catch CustomErrorType.errorReason2 {
    print("errorReason2")
}catch {                                // catch没有指定类型,那么可以匹配任何错误
    print("errorReason3")
}
                    </code></pre>
                </td>
            </tr>


            <tr>
                <td class='docs'> 4. 将错误转换成可选值 </td>
                <td class='code'>
                    <pre><code class='language-swift'>func someThrowingFunc(num: Int) throws -> Int { // 当num不为3的时候会抛异常,否则返回3

    defer {
        print("defer语句会在return,break,以及错误抛出之前执行")
    }

    defer {
        print("defer语句可以有多个,注意多个之间的执行顺序")
    }

    guard num == 3 else {
        throw CustomErrorType.errorReason1
    }

    return num
}

let x = try? someThrowingFunc(num: 3)   // 如果throwing函数抛出一个异常,那么x为nil
print(x)                                // Optional(3),x就是函数返回值

let y: Int?                             // 函数的返回值是Int
do {
    y = try someThrowingFunc(num: 2)
}catch CustomErrorType.errorReason1 {
    print("errorReason1")               // errorReason1
}

if let dataValue = try? someThrowingFunc(num: 2) { // 可以用try?写的更加简洁
    print(dataValue)
}else {
    print("dataValue为空")               // dataValue为空
}
                    </code></pre>
                </td>
            </tr>


            <tr>
                <td class='docs'> 5. 禁用错误传递:如果觉得这个地方肯定不会有错误抛出,可以禁用错误传递 </td>
                <td class='code'>
                    <pre><code class='language-swift'>let forbiddenX = try! someThrowingFunc(num: 3) // try?变为try!
                    </code></pre>
                </td>
            </tr>

            <tr>
                <td class='docs'> 6. defer语句:在异常抛出前,通常需要做一些操作,比如关闭文件,手动释放内存等,这些就可以在defer语句中执行 </td>
                <td class='code'>
                    <pre><code class='language-swift'>// defer语句会在return,break,以及错误抛出之前执行
// defer语句可以有多个
// defer语句必须要在throw语句前面才能执行
                    </code></pre>
                </td>
            </tr>


            <tr>
                <td class='docs'> 7. 使用断言:如果当前值缺失,或者不满足特定条件,可以使用断言使程序崩溃,并在控制台输出原因 </td>
                <td class='code'>
                    <pre><code class='language-swift'>var age = 3
assert(age > 0, "这个年龄不符合逻辑")     // 格式:assert(布尔表达式,"控制台输出内容")
age = -5
assert(age > 0, "这个年龄不符合逻辑")     // 程序奔溃, 布尔表达式为false时,使程序崩溃并输出内容
                    </code></pre>
                </td>
            </tr>


            </tbody>
        </table>
        <nav>
            <a href="../21-optional-chaining" class="prev" rel="prev">可选链式调用</a>
            <a href="../23-nested-types" class="next" rel="next">类型嵌套</a>
        </nav>

    </main>

    <footer>
        Powered by <a href="http://weibo.com/847309226">@Dariel在杭州</a>
        <a href="https://github.com/DarielChen/darielchen.github.io/tree/master/SwiftManual">source</a>
        Refer to <a href="https://twitter.com/BrettBukowski">@BrettBukowski</a>
    </footer>

</div>
<script async src="../source/site.js"></script>
<script src="../source/prism.js"></script>
</body>
</html>